# Generated by Django 5.1.1 on 2024-11-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('street_number', models.IntegerField()),
                ('street_name', models.TextField()),
                ('apartment_number', models.IntegerField()),
                ('zip_code', models.IntegerField()),
                ('dob', models.DateField()),
                ('reg_date', models.DateField()),
                ('party', models.TextField()),
                ('precinct_number', models.IntegerField()),
                ('voted_state', models.BooleanField()),
                ('voted_town_21', models.BooleanField()),
                ('voted_primary', models.BooleanField()),
                ('voted_general', models.BooleanField()),
                ('voted_town_23', models.BooleanField()),
                ('voter_score', models.BooleanField()),
            ],
        ),
    ]
